edit20210325/Controllers/Admin/CashInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using edit20210325.Function;
using edit20210325.Models;
using edit20210325.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace edit20210325.Controllers
{
    [Area(ProjectSet.AdminName)]
    public class CashInController : Controller
    {
        const int pageRowCount = 20;
        public IActionResult Index(string search = "", string searchSelect = "1", int page = 1, bool FuzzyOrNormal = false)
        {
            if (HttpContext.User.Claims.Count() == 0) return RedirectToAction("Index", "Login");
            var db = new CASE20210405Context();

            List<MemberCashInModel> lsSourceModels = db.MemberCashInModels.ToList();

            List<MemberModel> ModelList = db.MemberModels.ToList();

            List<MarkMemberCashInModel> lsModelout = ModelList.Join(
                lsSourceModels,
                m => Convert.ToString(m.Id),
                s => s.MemberCashInId,
                (m, s) => new MarkMemberCashInModel()
                {
                    Id = s.Id,
                    MemberEmail = m.MemberGmail,
                    MemberName = m.MemberName,
                    MemberCash = s.MemberCashInCash,
                    CaseName = s.MemberCashInName,
                    CaseRemarks = s.MemberCashInRemarks,
                    Space1 = s.MemberCashInSpace1,
                    Space2 = s.MemberCashInSpace2,
                    Space3 = s.MemberCashInSpace3,
                    CreateDate = s.MemberCashInCrtDate,
                    ChangeDate = s.MemberCashInChgDate
                }).OrderBy(c => c.Id).ToList();

            var pageCnt = page;
            var pageRows = pageRowCount;
            var querylsModel = lsModelout.Skip((pageCnt - 1) * pageRows).Take(pageRows);
            int listConut = (lsModelout.Count / pageRowCount) + 1;
            if (lsModelout.Count % pageRowCount > 0) listConut += 1;
            var pageNext = pageCnt + 1;
            if (pageNext >= listConut - 1) pageNext = listConut - 1;
            var pagePrev = pageCnt - 1;
            if (pagePrev <= 1) pagePrev = 1;
            ViewData["pageNext"] = pageNext;
            ViewData["pagePrev"] = pagePrev;
            int listConutStart = 0;
            int listConutEnd = 10;
            var pageRowsQuantity = 5;
            if (page <= pageRowsQuantity)
            {
                listConutStart = 1;
                listConutEnd = 10;
            }
            else
            {
                listConutStart = page - pageRowsQuantity;
                listConutEnd = page + pageRowsQuantity - 1;
            }
            if (listConutStart <= 1) listConutStart = 1;
            if (listConutEnd > listConut) listConutEnd = listConut - 1;
            ViewData["listConut"] = listConut;
            ViewData["page"] = page;
            ViewData["listConutStart"] = listConutStart;
            ViewData["listConutEnd"] = listConutEnd;
            ViewData["CountModel"] = querylsModel.Count();
            TempData["save"] = JsonConvert.SerializeObject(lsModelout);
            ViewData["search"] = search;
            ViewData["searchSelect"] = searchSelect;
            ViewData["FuzzyOrNormal"] = FuzzyOrNormal;
            return View(querylsModel);
        }

        public ActionResult SearchView(string search = "", string searchSelect = "1", int page = 1)
        {
            string strlsModel = (string)TempData["save"];
            List<MarkMemberCashInModel> lsModelout = JsonConvert.DeserializeObject<List<MarkMemberCashInModel>>(strlsModel);

            if (search == null) search = "";
            List<MarkMemberCashInModel> serachModelout;
            switch (searchSelect)
            {
                case "1":
                    serachModelout = lsModelout.Where(c => c.MemberEmail.Equals(search)).ToList();
                    break;
                case "2":
                    serachModelout = lsModelout.Where(c => c.MemberName.Equals(search)).ToList();
                    break;
                case "3":
                    serachModelout = lsModelout.Where(c => c.MemberCash.ToString().Equals(search)).ToList();
                    break;
                case "4":
                    serachModelout = lsModelout.Where(c => c.CaseName.Equals(search)).ToList();
                    break;
                case "5":
                    serachModelout = lsModelout.Where(c => c.CaseRemarks.Equals(search)).ToList();
                    break;
                case "6":
                    serachModelout = lsModelout.Where(c => c.Space1.Equals(search)).ToList();
                    break;
                case "7":
                    serachModelout = lsModelout.Where(c => c.Space2.Equals(search)).ToList();
                    break;
                case "8":
                    serachModelout = lsModelout.Where(c => c.Space3.Equals(search)).ToList();
                    break;
                case "9":
                    serachModelout = lsModelout.Where(c => c.CreateDate.Date.ToString("yyyy/MM/dd").Equals(search)).ToList();
                    break;
                case "10":
                    serachModelout = lsModelout.Where(c => c.ChangeDate.Date.ToString("yyyy/MM/dd").Equals(search)).ToList();
                    break;
                default:
                    serachModelout = lsModelout.Where(c => c.MemberEmail.Equals(search)).ToList();
                    break;
            }

            string JsonDataout = JsonConvert.SerializeObject(serachModelout);
            TempData["save"] = JsonDataout;
            ViewData["search"] = search;
            ViewData["searchSelect"] = searchSelect;
            ViewData["FuzzyOrNormal"] = true;
            var pageCnt = page;
            var pageRows = pageRowCount;
            var querylsModel = serachModelout.Skip((pageCnt - 1) * pageRows).Take(pageRows);
            int listConut = (serachModelout.Count / pageRowCount) + 1;
            if (serachModelout.Count % pageRowCount > 0) listConut += 1;
            var pageNext = pageCnt + 1;
            if (pageNext >= listConut - 1) pageNext = listConut - 1;
            var pagePrev = pageCnt - 1;
            if (pagePrev <= 1) pagePrev = 1;
            ViewData["pageNext"] = pageNext;
            ViewData["pagePrev"] = pagePrev;
            int listConutStart = 0;
            int listConutEnd = 10;
            var pageRowsQuantity = 5;
            if (page <= pageRowsQuantity)
            {
                listConutStart = 1;
                listConutEnd = 10;
            }
            else
            {
                listConutStart = page - pageRowsQuantity;
                listConutEnd = page + pageRowsQuantity - 1;
            }
            if (listConutStart <= 1) listConutStart = 1;
            if (listConutEnd > listConut) listConutEnd = listConut - 1;
            ViewData["listConut"] = listConut;
            ViewData["page"] = page;
            ViewData["listConutStart"] = listConutStart;
            ViewData["listConutEnd"] = listConutEnd;
            ViewData["CountModel"] = querylsModel.Count();
            return View(querylsModel);
        }

        public ActionResult FuzzySearchView(string search = "", string searchSelect = "1", int page = 1)
        {

            string strlsModel = (string)TempData["save"];
            List<MarkMemberCashInModel> lsModelout = JsonConvert.DeserializeObject<List<MarkMemberCashInModel>>(strlsModel);

            if (search == null) search = "";
            List<MarkMemberCashInModel> serachModelout;
            switch (searchSelect)
            {
                case "1":
                    serachModelout = lsModelout.Where(c => c.MemberEmail.IndexOf(search) > -1).ToList();
                    break;
                case "2":
                    serachModelout = lsModelout.Where(c => c.MemberName.IndexOf(search) > -1).ToList();
                    break;
                case "3":
                    serachModelout = lsModelout.Where(c => c.MemberCash.ToString().IndexOf(search) > -1).ToList();
                    break;
                case "4":
                    serachModelout = lsModelout.Where(c => c.CaseName.IndexOf(search) > -1).ToList();
                    break;
                case "5":
                    serachModelout = lsModelout.Where(c => c.CaseRemarks.IndexOf(search) > -1).ToList();
                    break;
                case "6":
                    serachModelout = lsModelout.Where(c => c.Space1.IndexOf(search) > -1).ToList();
                    break;
                case "7":
                    serachModelout = lsModelout.Where(c => c.Space2.IndexOf(search) > -1).ToList();
                    break;
                case "8":
                    serachModelout = lsModelout.Where(c => c.Space3.IndexOf(search) > -1).ToList();
                    break;
                case "9":
                    serachModelout = lsModelout.Where(c => c.CreateDate.Date.ToString("yyyy/MM/dd").IndexOf(search) > -1).ToList();
                    break;
                case "10":
                    serachModelout = lsModelout.Where(c => c.ChangeDate.Date.ToString("yyyy/MM/dd").IndexOf(search) > -1).ToList();
                    break;
                default:
                    serachModelout = lsModelout.Where(c => c.MemberEmail.IndexOf(search) > -1).ToList();
                    break;
            }

            string JsonDataout = JsonConvert.SerializeObject(serachModelout);
            TempData["save"] = JsonDataout;
            ViewData["search"] = search;
            ViewData["searchSelect"] = searchSelect;
            ViewData["FuzzyOrNormal"] = false;
            var pageCnt = page;
            var pageRows = pageRowCount;
            var querylsModel = serachModelout.Skip((pageCnt - 1) * pageRows).Take(pageRows);

edit20210325/Areas/AdminKfTBoRdp7z/Views/CashIn/Create.cshtml
@model edit20210325.Models.MemberCashInModel

@{
    ViewData["Title"] = "在製品建立";
    ViewData["ＰageCtrl"] = "1";
    var memberModels = (IEnumerable<edit20210325.Models.MemberModel>)ViewBag.ModelList;
    var gmails = memberModels.Select(r => r.MemberGmail).ToList();
    var names = memberModels.Select(r => r.MemberName).ToList();
}

<h1>在製品建立</h1>
<hr />
@*<script>
    $(document).ready(function () {
        changFunc();
    });
    function changFunc() {
        @{
            var json = Newtonsoft.Json.JsonConvert.SerializeObject((IEnumerable<edit20210325.Models.MemberModel>)ViewBag.ModelList);
         }
        var memberId = document.getElementById("MemberCashInId").value;
        var JsonString = @Html.Raw(json);
        for (var i = 0; i < JsonString.length; i++) {
            if (JsonString[i].Id == memberId) {
                document.getElementById("memberName").innerHTML = "會員名稱："+JsonString[i].MemberName;
            }
        }
    }
</script>*@
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderState" value=@ViewBag.OrderState class="form-control" />

            <div class="form-group">
                <label asp-for="MemberCashInMemberGmail" class="control-label"></label>
                <select asp-for="MemberCashInMemberGmail" class="form-control">                    
                    @foreach (var gmail in gmails)
                    {
                        <option value="@gmail">@gmail</option>
                    }
                </select>                
            </div>

            <div class="form-group">
                <select class="form-control" id="MemberName" name="MemberName" >       
                    @foreach (var name in names)
                    {
                        <option value="@name">@name</option>
                    }
                 </select>
             </div>

            <div class="form-group">
                <label asp-for="MemberCashInOrderID" class="control-label"></label>
                <input asp-for="MemberCashInOrderID" class="form-control-plaintext" />                
            </div>

            @*<div class="form-group">
                <label asp-for="MemberCashInId" class="control-label"></label>
                <select asp-for="MemberCashInId" class="form-control" onchange="changFunc()">
                    @{ var modelList = (IEnumerable<edit20210325.Models.MemberModel>)ViewBag.ModelList;}
                    @foreach (var it in modelList)
                    {
                        <option value="@it.Id">@it.MemberName@(": ")@it.MemberGmail</option>
                    }
                </select>
                <span asp-validation-for="MemberCashInId" class="text-danger"></span>
                <P id="memberName"></P>
            </div>*@

            <div class="form-group">
                <label asp-for="MemberCashInName" class="control-label"></label>
                <input asp-for="MemberCashInName" class="form-control" />
                <span asp-validation-for="MemberCashInName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MemberCashInVersion" class="control-label"></label>
                <input asp-for="MemberCashInVersion" class="form-control" value=@ViewBag.Version />
                <span asp-validation-for="MemberCashInVersion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MemberCashInCash" class="control-label"></label>
                <input asp-for="MemberCashInCash" class="form-control" value=@ViewBag.CashIn/>
                <span asp-validation-for="MemberCashInCash" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MemberCashInRemarks" class="control-label"></label><br>
                <textarea asp-for="MemberCashInRemarks" class="form-control" rows="6" cols="30"></textarea>
                <span asp-validation-for="MemberCashInRemarks" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MemberCashInCrtDate" class="control-label"></label>
                <input asp-for="MemberCashInCrtDate" type="date" asp-format="{0:yyyy-MM-dd}" class="form-control-plaintext" value=@ViewBag.Date />
                <span asp-validation-for="MemberCashInCrtDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MemberCashInChgDate" class="control-label"></label>
                <input asp-for="MemberCashInChgDate" type="date" asp-format="{0:yyyy-MM-dd}" class="form-control-plaintext" value=@ViewBag.Date />
                <span asp-validation-for="MemberCashInChgDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="建立" class="btn btn-primary onDivLeft" />
                <button id="btnExit" class="btn btn-primary onDivRight cancel" asp-action="exit">取消</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

edit20210325/Areas/AdminKfTBoRdp7z/Views/CashIn/Edit.cshtml
@model edit20210325.Models.MemberCashInModel

@{
    ViewData["Title"] = "在製品編輯";
    ViewData["ＰageCtrl"] = "1";
}

<h1>在製品編輯</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MemberCashInId" />
            <div class="form-group">

                @{
                    var member = (edit20210325.Models.MemberModel)ViewBag.member;
                }
                <p>@("會員名稱："+member.MemberName)</p>
                <p>@("會員帳號："+member.MemberGmail)</p>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="MemberCashInCash" />
                <label asp-for="MemberCashInCash" class="control-label"></label>
                <input disabled asp-for="MemberCashInCash" class="form-control" />
                <span asp-validation-for="MemberCashInCash" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberCashInName" class="control-label"></label>
                <input asp-for="MemberCashInName" class="form-control" />
                <span asp-validation-for="MemberCashInName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberCashInRemarks" class="control-label"></label><br>
                <textarea asp-for="MemberCashInRemarks" class="form-control" rows="6" cols="30"></textarea>
                <span asp-validation-for="MemberCashInRemarks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberCashInSpace1" class="control-label"></label><br>
                <textarea asp-for="MemberCashInSpace1" class="form-control" rows="6" cols="30"></textarea>
                <span asp-validation-for="MemberCashInSpace1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberCashInSpace2" class="control-label"></label><br>
                <textarea asp-for="MemberCashInSpace2" class="form-control" rows="6" cols="30"></textarea>
                <span asp-validation-for="MemberCashInSpace2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberCashInSpace3" class="control-label"></label><br>
                <textarea asp-for="MemberCashInSpace3" class="form-control" rows="6" cols="30"></textarea>
                <span asp-validation-for="MemberCashInSpace3" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="MemberCashInCrtDate" />
                <label asp-for="MemberCashInCrtDate" class="control-label"></label>
                <input disabled asp-for="MemberCashInCrtDate" type="date" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                <span asp-validation-for="MemberCashInCrtDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberCashInChgDate" class="control-label"></label>
                <input asp-for="MemberCashInChgDate" type="date" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                <span asp-validation-for="MemberCashInChgDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="儲存" class="btn btn-primary onDivLeft" />
                <button id="btnExit" class="btn btn-primary onDivRight cancel" asp-action="exit">取消</button>
            </div>
        </form>
    </div>
</div>


@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

edit20210325/Areas/AdminKfTBoRdp7z/Views/CashIn/FuzzySearchView.cshtml
@model IEnumerable<edit20210325.ViewModels.MarkMemberCashInModel>
@{
    var pathName = edit20210325.Function.ProjectSet.AdminName;
}
@{
    ViewData["Title"] = "在製品總表";
    ViewData["ＰageCtrl"] = "1";
}

<h1>在製品總表</h1>
<h4>查詢條件</h4>
<form class="form-inline  " role="form">
    <div class="form-group m-0 p-0 mr-auto">
        <label for="searchSelect">搜尋欄位:&ensp;</label>
        <select Name="searchSelect" id="searchSelectId" onchange="searchSelectFunc()">
            @if ((string)ViewData["searchSelect"] == "1")
            {
                <option value="1" selected>@Html.DisplayNameFor(model => model.MemberEmail)</option>
            }
            else
            {
                <option value="1">@Html.DisplayNameFor(model => model.MemberEmail)</option>
            }
            @if ((string)ViewData["searchSelect"] == "2")
            {
                <option value="2" selected>@Html.DisplayNameFor(model => model.MemberName)</option>
            }
            else
            {
                <option value="2">@Html.DisplayNameFor(model => model.MemberName)</option>
            }
            @if ((string)ViewData["searchSelect"] == "3")
            {
                <option value="3" selected>@Html.DisplayNameFor(model => model.MemberCash)</option>

            }
            else
            {
                <option value="3">@Html.DisplayNameFor(model => model.MemberCash)</option>

            }
            @if ((string)ViewData["searchSelect"] == "4")
            {
                <option value="4" selected>@Html.DisplayNameFor(model => model.CaseName)</option>

            }
            else
            {
                <option value="4">@Html.DisplayNameFor(model => model.CaseName)</option>

            }
            @if ((string)ViewData["searchSelect"] == "5")
            {
                <option value="5" selected>@Html.DisplayNameFor(model => model.CaseRemarks)</option>

            }
            else
            {
                <option value="5">@Html.DisplayNameFor(model => model.CaseRemarks)</option>

            }
            @if ((string)ViewData["searchSelect"] == "6")
            {
                <option value="6" selected>@Html.DisplayNameFor(model => model.Space1)</option>

            }
            else
            {
                <option value="6">@Html.DisplayNameFor(model => model.Space1)</option>

            }
            @if ((string)ViewData["searchSelect"] == "7")
            {
                <option value="7" selected>@Html.DisplayNameFor(model => model.Space2)</option>

            }
            else
            {
                <option value="7">@Html.DisplayNameFor(model => model.Space2)</option>

            }
            @if ((string)ViewData["searchSelect"] == "8")
            {
                <option value="8" selected>@Html.DisplayNameFor(model => model.Space3)</option>

            }
            else
            {
                <option value="8">@Html.DisplayNameFor(model => model.Space3)</option>

            }
            @if ((string)ViewData["searchSelect"] == "9")
            {
                <option value="9" selected>@Html.DisplayNameFor(model => model.CreateDate)</option>

            }
            else
            {
                <option value="9">@Html.DisplayNameFor(model => model.CreateDate)</option>

            }
            @if ((string)ViewData["searchSelect"] == "10")
            {
                <option value="10" selected>@Html.DisplayNameFor(model => model.ChangeDate)</option>

            }
            else
            {
                <option value="10">@Html.DisplayNameFor(model => model.ChangeDate)</option>

            }
        </select>
    </div>
    <div class=" form-group  m-0 p-0">
        <label for="search" style="width:auto">關鍵字:&ensp;</label>
        <input type="text" name="search" id="searchId" value="@ViewData["search"]" />&ensp;
    </div>
    <div class=" form-group  m1-1 p-0 ">
        <label class="m-0 p-0" for="RadioModelId">比對模式:</label>
        <div class="form-control-sm">
            @Html.RadioButton("RadioModelId", "fuzzyMatch", true, new { id = "RadioModelId2", @class = " p-0" })包含關鍵字<br>
            @Html.RadioButton("RadioModelId", "keyMatch", false, new { id = "RadioModelId1", @class = "p-0" })關鍵字相同<br>
        </div>
    </div>
    <div class=" form-group  m-0 p-0  m1-2 ">
        <input type="button" value="開始搜尋" onclick="SearchFunc('CashIn','@pathName')" />
    </div>


</form>
<hr style="background-color:#808080">
<div class="form-inline">
    <input type="button" class="mb-1 mr-auto" value="檢視所有資料" onclick="location.href='@Url.Action("Index", "CashIn",new { FuzzyOrNormal = false,search = (string)ViewData["search"], searchSelect = (string)ViewData["searchSelect"],page=1})'" />
</div>



<table class="table tbl-list" style="border:2px  #808080 solid; width:100%" id="tableId" cellpadding="0" cellspacing="0">
    <thead>
        <tr style="background-color: #c7c7c7;">
            <th style="border:1px  #808080 solid;"></th>
            <th style="border:1px  #808080 solid;"></th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 2, 'string')">
                @Html.DisplayNameFor(model => model.MemberEmail)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 3, 'string')">
                @Html.DisplayNameFor(model => model.MemberName)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 4, 'string')">
                @Html.DisplayNameFor(model => model.MemberCash)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 5, 'string')">
                @Html.DisplayNameFor(model => model.CaseName)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 6, 'string')">
                @Html.DisplayNameFor(model => model.CaseRemarks)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 7, 'string')">
                @Html.DisplayNameFor(model => model.Space1)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 8, 'string')">
                @Html.DisplayNameFor(model => model.Space2)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 9, 'string')">
                @Html.DisplayNameFor(model => model.Space3)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 10, 'string')">
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 11, 'string')">
                @Html.DisplayNameFor(model => model.ChangeDate)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <!--@Html.ActionLink("編輯", "Edit", new {  id=item.Id  })    -->
                <input type="button" value="編輯" onclick="location.href='@Url.Action("Edit", "CashIn", new {  id=item.Id  })'" />
            </td>
            <td>
                <!--@Html.ActionLink("刪除", "Delete", new {  id=item.Id})-->
                <input type="button" value="刪除" onclick="Delete('@item.MemberName', '@Url.Action("Delete", "CashIn", new {  id=item.Id  })')" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberCash)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CaseName)
            </td>
            <td>
<textarea style="resize: none;border:0px;" rows="6" cols="10" readonly>
@Html.DisplayFor(modelItem => item.CaseRemarks)
</textarea>
            </td>
            <td>
<textarea style="resize: none;border:0px;" rows="3" cols="10" readonly>
@Html.DisplayFor(modelItem => item.Space1)
</textarea>
            </td>
            <td>
<textarea style="resize: none;border:0px;" rows="6" cols="10" readonly>
 @Html.DisplayFor(modelItem => item.Space2)
</textarea>
            </td>
            <td>
<textarea style="resize: none;border:0px;" rows="6" cols="10" readonly>
 @Html.DisplayFor(modelItem => item.Space3)
</textarea>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChangeDate)
            </td>
        </tr>
        }
    </tbody>
</table>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item ">
            @if ((int)ViewData["CountModel"] > 0)
            {
                <button class="page-link" onclick="location.href='@Url.Action("FuzzySearchView", "CashIn", new { search = ViewData["search"], searchSelect = ViewData["searchSelect"], page = ViewData["pagePrev"] })'">&lt;</button>
            }
        </li>

        @for (int i = (int)ViewData["listConutStart"]; i <= (int)ViewData["listConutEnd"]; i++)
        {
            if (i == (int)ViewData["page"])
            {
                <li class="page-item">
                    <label class="page-link" style="color:red" onclick="location.href='@Url.Action("FuzzySearchView", "CashIn", new { search=ViewData["search"],searchSelect=ViewData["searchSelect"],  page=i })'">&ensp;[@i]&ensp;</label>
                </li>
            }
            else
            {
                <li class="page-item">
                    <label class="page-link" style="color:black" onclick="location.href='@Url.Action("FuzzySearchView", "CashIn", new { search=ViewData["search"],searchSelect=ViewData["searchSelect"],  page=i })'">&ensp;[@i]&ensp;</label>
                </li>
            }
        }
        <li class="page-item">
            @if ((int)ViewData["CountModel"] > 0)
            {
                <button class="page-link" onclick="location.href='@Url.Action("FuzzySearchView", "CashIn", new {search=ViewData["search"],searchSelect=ViewData["searchSelect"],   page= ViewData["pageNext"] })'">&gt;</button>
            }
        </li>
    </ul>
</nav>