edit20210325/Controllers/Admin/DepositOrderLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using edit20210325.Models;
using edit20210325.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace edit20210325.Controllers.Admin
{
    [Area(Function.ProjectSet.AdminName)]
    public class DepositOrderLogController : Controller
    {
        const int pageRowCount = 20;
        public IActionResult Index(string search = "", string searchSelect = "1", int page = 1, bool FuzzyOrNormal = false)
        {
            if (HttpContext.User.Claims.Count() == 0) return RedirectToAction("Index", "Login");
            var db = new CASE20210405Context();

            List<DepositOrderLogModel> lsSourceModels = db.DepositOrderLogModels.ToList();
            List<MemberCashInModel> lsMemberCashInModels = db.MemberCashInModels.ToList();

            List<MemberModel> ModelList = db.MemberModels.ToList();

            List<MarkDepositOrderLogModel> lsModelout = ModelList.Join(
                lsSourceModels,
                m => Convert.ToString(m.Id),
                s => s.MemberId,
                (m, s) => new
                {
                    Id = s.Id,
                    MemberEmail = m.MemberGmail,
                    MemberName = m.MemberName,
                    MemberCash = s.MemberCashInCash,
                    CaseId = s.CashInId,
                    CaseRemarks1 = s.MemberCashInRemarks1,
                    CaseRemarks2 = s.MemberCashInRemarks2,
                    CreateDate = s.MemberCashInCrtDate,
                }).Join(
                lsMemberCashInModels,
                c => c.CaseId,
                r => Convert.ToString(r.Id),
                (c, r) => new MarkDepositOrderLogModel()
                {
                    Id = c.Id,
                    MemberEmail = c.MemberEmail,
                    MemberName = c.MemberName,
                    MemberCash = c.MemberCash,
                    CaseName = r.MemberCashInName,
                    CaseRemarks1 = c.CaseRemarks1,
                    CaseRemarks2 = c.CaseRemarks2,
                    CreateDate = c.CreateDate
                }
                ).OrderBy(c => c.Id).ToList();

            var pageCnt = page;
            var pageRows = pageRowCount;
            var querylsModel = lsModelout.Skip((pageCnt - 1) * pageRows).Take(pageRows);
            int listConut = (lsModelout.Count / pageRowCount) + 1;
            if (lsModelout.Count % pageRowCount > 0) listConut += 1;
            var pageNext = pageCnt + 1;
            if (pageNext >= listConut - 1) pageNext = listConut - 1;
            var pagePrev = pageCnt - 1;
            if (pagePrev <= 1) pagePrev = 1;
            ViewData["pageNext"] = pageNext;
            ViewData["pagePrev"] = pagePrev;
            int listConutStart = 0;
            int listConutEnd = 10;
            var pageRowsQuantity = 5;
            if (page <= pageRowsQuantity)
            {
                listConutStart = 1;
                listConutEnd = 10;
            }
            else
            {
                listConutStart = page - pageRowsQuantity;
                listConutEnd = page + pageRowsQuantity - 1;
            }
            if (listConutStart <= 1) listConutStart = 1;
            if (listConutEnd > listConut) listConutEnd = listConut - 1;
            ViewData["listConut"] = listConut;
            ViewData["page"] = page;
            ViewData["listConutStart"] = listConutStart;
            ViewData["listConutEnd"] = listConutEnd;
            ViewData["CountModel"] = querylsModel.Count();
            TempData["save"] = JsonConvert.SerializeObject(lsModelout);
            ViewData["search"] = search;
            ViewData["searchSelect"] = searchSelect;
            ViewData["FuzzyOrNormal"] = FuzzyOrNormal;
            return View(querylsModel);
        }

        public ActionResult SearchView(string search = "", string searchSelect = "1", int page = 1)
        {
            string strlsModel = (string)TempData["save"];
            List<MarkDepositOrderLogModel> lsModelout = JsonConvert.DeserializeObject<List<MarkDepositOrderLogModel>>(strlsModel);

            if (search == null) search = "";
            List<MarkDepositOrderLogModel> serachModelout;
            switch (searchSelect)
            {
                case "1":
                    serachModelout = lsModelout.Where(c => c.MemberEmail.Equals(search)).ToList();
                    break;
                case "2":
                    serachModelout = lsModelout.Where(c => c.MemberName.Equals(search)).ToList();
                    break;
                case "3":
                    serachModelout = lsModelout.Where(c => c.MemberCash.ToString().Equals(search)).ToList();
                    break;
                case "4":
                    serachModelout = lsModelout.Where(c => c.CaseName.Equals(search)).ToList();
                    break;
                case "5":
                    serachModelout = lsModelout.Where(c => c.CaseRemarks1.Equals(search)).ToList();
                    break;
                case "6":
                    serachModelout = lsModelout.Where(c => c.CaseRemarks2.Equals(search)).ToList();
                    break;
                case "7":
                    serachModelout = lsModelout.Where(c => c.CreateDate.Date.ToString("yyyy/MM/dd").Equals(search)).ToList();
                    break;
                default:
                    serachModelout = lsModelout.Where(c => c.MemberEmail.Equals(search)).ToList();
                    break;
            }

            string JsonDataout = JsonConvert.SerializeObject(serachModelout);
            TempData["save"] = JsonDataout;
            ViewData["search"] = search;
            ViewData["searchSelect"] = searchSelect;
            ViewData["FuzzyOrNormal"] = true;
            var pageCnt = page;
            var pageRows = pageRowCount;
            var querylsModel = serachModelout.Skip((pageCnt - 1) * pageRows).Take(pageRows);
            int listConut = (serachModelout.Count / pageRowCount) + 1;
            if (serachModelout.Count % pageRowCount > 0) listConut += 1;
            var pageNext = pageCnt + 1;
            if (pageNext >= listConut - 1) pageNext = listConut - 1;
            var pagePrev = pageCnt - 1;
            if (pagePrev <= 1) pagePrev = 1;
            ViewData["pageNext"] = pageNext;
            ViewData["pagePrev"] = pagePrev;
            int listConutStart = 0;
            int listConutEnd = 10;
            var pageRowsQuantity = 5;
            if (page <= pageRowsQuantity)
            {
                listConutStart = 1;
                listConutEnd = 10;
            }
            else
            {
                listConutStart = page - pageRowsQuantity;
                listConutEnd = page + pageRowsQuantity - 1;
            }
            if (listConutStart <= 1) listConutStart = 1;
            if (listConutEnd > listConut) listConutEnd = listConut - 1;
            ViewData["listConut"] = listConut;
            ViewData["page"] = page;
            ViewData["listConutStart"] = listConutStart;
            ViewData["listConutEnd"] = listConutEnd;
            ViewData["CountModel"] = querylsModel.Count();
            return View(querylsModel);
        }

        public ActionResult FuzzySearchView(string search = "", string searchSelect = "1", int page = 1)
        {

            string strlsModel = (string)TempData["save"];
            List<MarkDepositOrderLogModel> lsModelout = JsonConvert.DeserializeObject<List<MarkDepositOrderLogModel>>(strlsModel);

            if (search == null) search = "";
            List<MarkDepositOrderLogModel> serachModelout;
            switch (searchSelect)
            {
                case "1":
                    serachModelout = lsModelout.Where(c => c.MemberEmail.IndexOf(search) > -1).ToList();
                    break;
                case "2":
                    serachModelout = lsModelout.Where(c => c.MemberName.IndexOf(search) > -1).ToList();
                    break;
                case "3":
                    serachModelout = lsModelout.Where(c => c.MemberCash.ToString().IndexOf(search) > -1).ToList();
                    break;
                case "4":
                    serachModelout = lsModelout.Where(c => c.CaseName.IndexOf(search) > -1).ToList();
                    break;
                case "5":
                    serachModelout = lsModelout.Where(c => c.CaseRemarks1.IndexOf(search) > -1).ToList();
                    break;
                case "6":
                    serachModelout = lsModelout.Where(c => c.CaseRemarks2.IndexOf(search) > -1).ToList();
                    break;
                case "7":
                    serachModelout = lsModelout.Where(c => c.CreateDate.Date.ToString("yyyy/MM/dd").IndexOf(search) > -1).ToList();
                    break;
                default:
                    serachModelout = lsModelout.Where(c => c.MemberEmail.IndexOf(search) > -1).ToList();
                    break;
            }

            string JsonDataout = JsonConvert.SerializeObject(serachModelout);
            TempData["save"] = JsonDataout;
            ViewData["search"] = search;
            ViewData["searchSelect"] = searchSelect;
            ViewData["FuzzyOrNormal"] = false;
            var pageCnt = page;
            var pageRows = pageRowCount;
            var querylsModel = serachModelout.Skip((pageCnt - 1) * pageRows).Take(pageRows);
            int listConut = (serachModelout.Count / pageRowCount) + 1;
            if (serachModelout.Count % pageRowCount > 0) listConut += 1;
            var pageNext = pageCnt + 1;
            if (pageNext >= listConut - 1) pageNext = listConut - 1;
            var pagePrev = pageCnt - 1;
            if (pagePrev <= 1) pagePrev = 1;
            ViewData["pageNext"] = pageNext;
            ViewData["pagePrev"] = pagePrev;
            int listConutStart = 0;

edit20210325/Areas/AdminKfTBoRdp7z/Views/DepositOrderLog/FuzzySearchView.cshtml
@model IEnumerable<edit20210325.ViewModels.MarkDepositOrderLogModel>
@{
    var pathName = edit20210325.Function.ProjectSet.AdminName;
}
@{
    ViewData["Title"] = "在製品消費紀錄";
    ViewData["ＰageCtrl"] = "2";
}

<h1>在製品消費紀錄</h1>
<h4>查詢條件</h4>
<form class="form-inline  " role="form">
    <div class="form-group m-0 p-0 mr-auto">
        <label for="searchSelect">搜尋欄位:&ensp;</label>
        <select Name="searchSelect" id="searchSelectId">
            @if ((string)ViewData["searchSelect"] == "1")
            {
                <option value="1" selected>@Html.DisplayNameFor(model => model.MemberEmail)</option>
            }
            else
            {
                <option value="1">@Html.DisplayNameFor(model => model.MemberEmail)</option>
            }
            @if ((string)ViewData["searchSelect"] == "2")
            {
                <option value="2" selected>@Html.DisplayNameFor(model => model.MemberName)</option>
            }
            else
            {
                <option value="2">@Html.DisplayNameFor(model => model.MemberName)</option>
            }
            @if ((string)ViewData["searchSelect"] == "3")
            {
                <option value="3" selected>@Html.DisplayNameFor(model => model.MemberCash)</option>

            }
            else
            {
                <option value="3">@Html.DisplayNameFor(model => model.MemberCash)</option>

            }
            @if ((string)ViewData["searchSelect"] == "4")
            {
                <option value="4" selected>@Html.DisplayNameFor(model => model.CaseName)</option>

            }
            else
            {
                <option value="4">@Html.DisplayNameFor(model => model.CaseName)</option>

            }
            @if ((string)ViewData["searchSelect"] == "5")
            {
                <option value="5" selected>@Html.DisplayNameFor(model => model.CaseRemarks1)</option>

            }
            else
            {
                <option value="5">@Html.DisplayNameFor(model => model.CaseRemarks1)</option>

            }
            @if ((string)ViewData["searchSelect"] == "6")
            {
                <option value="6" selected>@Html.DisplayNameFor(model => model.CaseRemarks2)</option>

            }
            else
            {
                <option value="6">@Html.DisplayNameFor(model => model.CaseRemarks2)</option>

            }
            @if ((string)ViewData["searchSelect"] == "7")
            {
                <option value="7" selected>@Html.DisplayNameFor(model => model.CreateDate)</option>

            }
            else
            {
                <option value="7">@Html.DisplayNameFor(model => model.CreateDate)</option>

            }
        </select>
    </div>
    <div class=" form-group  m-0 p-0">
        <label for="search" style="width:auto">關鍵字:&ensp;</label>
        <input type="text" name="search" id="searchId" value="@ViewData["search"]" />&ensp;
    </div>
    <div class=" form-group  m1-1 p-0 ">
        <label class="m-0 p-0" for="RadioModelId">比對模式:</label>
        <div class="form-control-sm">
            @Html.RadioButton("RadioModelId", "fuzzyMatch", true, new { id = "RadioModelId2", @class = " p-0" })包含關鍵字<br>
            @Html.RadioButton("RadioModelId", "keyMatch", false, new { id = "RadioModelId1", @class = "p-0" })關鍵字相同<br>
        </div>
    </div>
    <div class=" form-group  m-0 p-0  m1-2 ">
        <input type="button" value="開始搜尋" onclick="SearchFunc('DepositOrderLog','@pathName')" />
    </div>


</form>
<hr style="background-color:#808080">
<div class="form-inline">
    <input type="button" class="mb-1 mr-auto" value="檢視所有資料" onclick="location.href='@Url.Action("Index", "DepositOrderLog",new { FuzzyOrNormal = false,search = (string)ViewData["search"], searchSelect = (string)ViewData["searchSelect"],page=1})'" />
    <input type="button" class="mb-1" value="新增在製品消費紀錄" onclick="location.href='@Url.Action("Create", "DepositOrderLog")'" />
</div>



<table class="table tbl-list" style="border:2px  #808080 solid; width:100%" id="tableId" cellpadding="0" cellspacing="0">
    <thead>
        <tr style="background-color: #c7c7c7;">
            <th style="border:1px  #808080 solid;"></th>
            <th style="border:1px  #808080 solid;"></th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 2, 'string')">
                @Html.DisplayNameFor(model => model.MemberEmail)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 3, 'string')">
                @Html.DisplayNameFor(model => model.MemberName)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 4, 'string')">
                @Html.DisplayNameFor(model => model.MemberCash)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 5, 'string')">
                @Html.DisplayNameFor(model => model.CaseName)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 6, 'string')">
                @Html.DisplayNameFor(model => model.CaseRemarks1)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 7, 'string')">
                @Html.DisplayNameFor(model => model.CaseRemarks2)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 8, 'string')">
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <!--@Html.ActionLink("編輯", "Edit", new {  id=item.Id  })    -->
                <input type="button" value="編輯" onclick="location.href='@Url.Action("Edit", "DepositOrderLog", new {  id=item.Id  })'" />
            </td>
            <td>
                <!--@Html.ActionLink("刪除", "Delete", new {  id=item.Id})-->
                <input type="button" value="刪除" onclick="Delete('@item.MemberName', '@Url.Action("Delete", "DepositOrderLog", new {  id=item.Id  })')" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberCash)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CaseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CaseRemarks1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CaseRemarks2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
        </tr>
        }
    </tbody>
</table>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item ">
            @if ((int)ViewData["CountModel"] > 0)
            {
                <button class="page-link" onclick="location.href='@Url.Action("FuzzySearchView", "DepositOrderLog", new { search = ViewData["search"], searchSelect = ViewData["searchSelect"], page = ViewData["pagePrev"] })'">&lt;</button>
            }
        </li>

        @for (int i = (int)ViewData["listConutStart"]; i <= (int)ViewData["listConutEnd"]; i++)
        {
            if (i == (int)ViewData["page"])
            {
                <li class="page-item">
                    <label class="page-link" style="color:red" onclick="location.href='@Url.Action("FuzzySearchView", "DepositOrderLog", new { search=ViewData["search"],searchSelect=ViewData["searchSelect"],  page=i })'">&ensp;[@i]&ensp;</label>
                </li>
            }
            else
            {
                <li class="page-item">
                    <label class="page-link" style="color:black" onclick="location.href='@Url.Action("FuzzySearchView", "DepositOrderLog", new { search=ViewData["search"],searchSelect=ViewData["searchSelect"],  page=i })'">&ensp;[@i]&ensp;</label>
                </li>
            }
        }
        <li class="page-item">
            @if ((int)ViewData["CountModel"] > 0)
            {
                <button class="page-link" onclick="location.href='@Url.Action("FuzzySearchView", "DepositOrderLog", new {search=ViewData["search"],searchSelect=ViewData["searchSelect"],   page= ViewData["pageNext"] })'">&gt;</button>
            }
        </li>
    </ul>
</nav>

edit20210325/Areas/AdminKfTBoRdp7z/Views/DepositOrderLog/Index.cshtml
@model IEnumerable<edit20210325.ViewModels.MarkDepositOrderLogModel>
@{
    var pathName = edit20210325.Function.ProjectSet.AdminName;
}
@{
    ViewData["Title"] = "在製品消費紀錄";
    ViewData["ＰageCtrl"] = "2";
}

<h1>在製品消費紀錄</h1>
<h4>查詢條件</h4>
<form class="form-inline  " role="form">
    <div class="form-group m-0 p-0 mr-auto">
        <label for="searchSelect">搜尋欄位:&ensp;</label>
        <div class="form-group m-0 p-0 mr-auto">
            <label for="searchSelect">搜尋欄位:&ensp;</label>
            <select Name="searchSelect" id="searchSelectId">
                @if ((string)ViewData["searchSelect"] == "1")
                {
                    <option value="1" selected>@Html.DisplayNameFor(model => model.MemberEmail)</option>
                }
                else
                {
                    <option value="1">@Html.DisplayNameFor(model => model.MemberEmail)</option>
                }
                @if ((string)ViewData["searchSelect"] == "2")
                {
                    <option value="2" selected>@Html.DisplayNameFor(model => model.MemberName)</option>
                }
                else
                {
                    <option value="2">@Html.DisplayNameFor(model => model.MemberName)</option>
                }
                @if ((string)ViewData["searchSelect"] == "3")
                {
                    <option value="3" selected>@Html.DisplayNameFor(model => model.MemberCash)</option>

                }
                else
                {
                    <option value="3">@Html.DisplayNameFor(model => model.MemberCash)</option>

                }
                @if ((string)ViewData["searchSelect"] == "4")
                {
                    <option value="4" selected>@Html.DisplayNameFor(model => model.CaseName)</option>

                }
                else
                {
                    <option value="4">@Html.DisplayNameFor(model => model.CaseName)</option>

                }
                @if ((string)ViewData["searchSelect"] == "5")
                {
                    <option value="5" selected>@Html.DisplayNameFor(model => model.CaseRemarks1)</option>

                }
                else
                {
                    <option value="5">@Html.DisplayNameFor(model => model.CaseRemarks1)</option>

                }
                @if ((string)ViewData["searchSelect"] == "6")
                {
                    <option value="6" selected>@Html.DisplayNameFor(model => model.CaseRemarks2)</option>

                }
                else
                {
                    <option value="6">@Html.DisplayNameFor(model => model.CaseRemarks2)</option>

                }
                @if ((string)ViewData["searchSelect"] == "7")
                {
                    <option value="7" selected>@Html.DisplayNameFor(model => model.CreateDate)</option>

                }
                else
                {
                    <option value="7">@Html.DisplayNameFor(model => model.CreateDate)</option>

                }
            </select>
        </div>
    </div>
    <div class=" form-group  m-0 p-0">
        <label for="search" style="width:auto">關鍵字:&ensp;</label>
        <input type="text" name="search" id="searchId" value="@ViewData["search"]">&ensp;
    </div>
    <div class=" form-group  m1-1 p-0 ">
        <label class="m-0 p-0" for="RadioModelId">比對模式:</label>
        <div class="form-control-sm">
            @if (!(bool)ViewData["FuzzyOrNormal"])
            {
                @Html.RadioButton("RadioModelId", "fuzzyMatch", true, new { id = "RadioModelId2", @class = " p-0" })
                @("包含關鍵字")<br>
                @Html.RadioButton("RadioModelId", "keyMatch", false, new { id = "RadioModelId1", @class = "p-0" })
                @("關鍵字相同")<br>
            }
            else
            {
                @Html.RadioButton("RadioModelId", "fuzzyMatch", false, new { id = "RadioModelId2", @class = " p-0" })
                @("包含關鍵字")<br>
                @Html.RadioButton("RadioModelId", "keyMatch", true, new { id = "RadioModelId1", @class = "p-0" })
                @("關鍵字相同")<br>
            }

        </div>
    </div>
    <div class=" form-group  m-0 p-0  m1-2 ">
        <input type="button" value="開始搜尋" onclick="SearchFunc('DepositOrderLog','@pathName')" />
    </div>
</form>
<hr style="background-color:#808080">
<div class="form-inline">
    <input type="button" class="mb-1 mr-auto" value="檢視所有資料" onclick="location.href='@Url.Action("Index", "DepositOrderLog",new {  FuzzyOrNormal=(bool)ViewData["FuzzyOrNormal"],search = (string)ViewData["search"], searchSelect = (string)ViewData["searchSelect"],page=1})'" />
    <input type="button" class="mb-1" value="新增在製品消費紀錄" onclick="location.href='@Url.Action("Create", "DepositOrderLog")'" />
</div>

<table class="table tbl-list" style="border:2px  #808080 solid; width:100%" id="tableId" cellpadding="0" cellspacing="0">
    <thead>
        <tr style="background-color: #c7c7c7;">
            <th style="border:1px  #808080 solid;"></th>
            <th style="border:1px  #808080 solid;"></th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 2, 'string')">
                @Html.DisplayNameFor(model => model.MemberEmail)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 3, 'string')">
                @Html.DisplayNameFor(model => model.MemberName)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 4, 'string')">
                @Html.DisplayNameFor(model => model.MemberCash)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 5, 'string')">
                @Html.DisplayNameFor(model => model.CaseName)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 6, 'string')">
                @Html.DisplayNameFor(model => model.CaseRemarks1)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 7, 'string')">
                @Html.DisplayNameFor(model => model.CaseRemarks2)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 8, 'string')">
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <!--@Html.ActionLink("編輯", "Edit", new {  id=item.Id  })    -->
                    <input type="button" value="編輯" onclick="location.href='@Url.Action("Edit", "DepositOrderLog", new {  id=item.Id  })'" />
                </td>
                <td>
                    <!--@Html.ActionLink("刪除", "Delete", new {  id=item.Id})-->
                    <input type="button" value="刪除" onclick="Delete('@item.MemberName', '@Url.Action("Delete", "DepositOrderLog", new {  id=item.Id  })')" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberCash)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CaseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CaseRemarks1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CaseRemarks2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
            </tr>
        }
    </tbody>
</table>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item ">
            @if ((int)ViewData["CountModel"] > 0)
            {
                <button class="page-link" onclick="location.href='@Url.Action("Index", "DepositOrderLog", new { search = ViewData["search"], searchSelect = ViewData["searchSelect"], page = ViewData["pagePrev"] })'">&lt;</button>
            }
        </li>

        @for (int i = (int)ViewData["listConutStart"]; i <= (int)ViewData["listConutEnd"]; i++)
        {
            if (i == (int)ViewData["page"])
            {
                <li class="page-item">
                    <label class="page-link" style="color:red" onclick="location.href='@Url.Action("Index", "DepositOrderLog", new { search=ViewData["search"],searchSelect=ViewData["searchSelect"],  page=i })'">&ensp;[@i]&ensp;</label>
                </li>
            }
            else
            {
                <li class="page-item">
                    <label class="page-link" style="color:black" onclick="location.href='@Url.Action("Index", "DepositOrderLog", new { search=ViewData["search"],searchSelect=ViewData["searchSelect"],  page=i })'">&ensp;[@i]&ensp;</label>
                </li>
            }
        }
        <li class="page-item">
            @if ((int)ViewData["CountModel"] > 0)
            {
                <button class="page-link" onclick="location.href='@Url.Action("Index", "DepositOrderLog", new {search=ViewData["search"],searchSelect=ViewData["searchSelect"],   page= ViewData["pageNext"] })'">&gt;</button>
            }
        </li>
    </ul>
</nav>