edit20210325/Controllers/Admin/SalesOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using edit20210325.Models;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using edit20210325.ViewModels;
using edit20210325.Function;

namespace edit20210325.Controllers
{
    [Area(ProjectSet.AdminName)]
    public class SalesOrderController : Controller
    {
        const int pageRowCount = 20;

        public ActionResult Index(string search = "", string searchSelect = "1", int page = 1,bool FuzzyOrNormal = false )
        {
            if (HttpContext.User.Claims.Count() == 0) return RedirectToAction("Index", "Login");
            var db = new CASE20210405Context();

            List<SalesOrderModel> lsSourceModels = db.SalesOrderModels.ToList();

            List<MemberModel> ModelList = db.MemberModels.ToList();

            List<MarkSalesOrderModel> lsModelout = ModelList.Join(
                lsSourceModels,
                m => Convert.ToString(m.Id),
                s => s.MemberId,
                (m, s) => new MarkSalesOrderModel()
                {
                    Id = s.Id,
                    MemberEmail = m.MemberGmail,
                    MemberName = m.MemberName,
                    ProductName = s.ProductName,
                    ProductInfo = s.ProductInfo,
                    ProductCharge = s.ProductCharge,
                    ProductCounts = s.ProductCounts,
                    ProductUnitDays = s.ProductUnitDays,
                    ProductUnitPrice = s.ProductUnitPrice,
                    ProductRemarks1 = s.ProductRemarks1,
                    ProductRemarks2 = s.ProductRemarks2,
                    ProductDays = s.ProductDays,
                    ProductCreateDate = s.ProductCreateDate,
                    ProductChangeDate = s.ProductChangeDate
                }).OrderBy(c => c.Id).ToList();


            var pageCnt = page;
            var pageRows = pageRowCount;
            var querylsModel = lsModelout.Skip((pageCnt - 1) * pageRows).Take(pageRows);
            int listConut = (lsModelout.Count / pageRowCount) + 1;
            if (lsModelout.Count % pageRowCount > 0) listConut += 1;
            var pageNext = pageCnt + 1;
            if (pageNext >= listConut - 1) pageNext = listConut - 1;
            var pagePrev = pageCnt -1;
            if (pagePrev <= 1) pagePrev = 1;
            ViewData["pageNext"] = pageNext;
            ViewData["pagePrev"] = pagePrev;
            int listConutStart = 0;
            int listConutEnd = 10;
            var pageRowsQuantity = 5;
            if (page <= pageRowsQuantity)
            {
                listConutStart = 1;
                listConutEnd = 10;
            }
            else
            {
                listConutStart = page - pageRowsQuantity;
                listConutEnd = page + pageRowsQuantity-1;
            }
            if (listConutStart <= 1) listConutStart = 1;
            if (listConutEnd > listConut) listConutEnd = listConut-1;
            ViewData["listConut"] = listConut;
            ViewData["page"] = page;
            ViewData["listConutStart"] = listConutStart;
            ViewData["listConutEnd"] = listConutEnd;
            ViewData["CountModel"] = querylsModel.Count();
            TempData["save"] = JsonConvert.SerializeObject(lsModelout);
            ViewData["search"] = search;
            ViewData["searchSelect"] = searchSelect;
            ViewData["FuzzyOrNormal"] = FuzzyOrNormal;
            return View(querylsModel);
        }
        
        public ActionResult SearchView(string search="" , string searchSelect="1", int page = 1)
        {
            string strlsModel = (string)TempData["save"];
            List<MarkSalesOrderModel> lsModelout = JsonConvert.DeserializeObject<List<MarkSalesOrderModel>>(strlsModel);
          
            if (search == null) search = "";
            List<MarkSalesOrderModel> serachModelout;
            switch (searchSelect)
            {
                case "1":
                    serachModelout = lsModelout.Where(c => c.MemberEmail.Equals(search)).ToList();
                    break;
                case "2":
                    serachModelout = lsModelout.Where(c => c.MemberName.Equals(search)).ToList();
                    break;
                case "3":
                    serachModelout = lsModelout.Where(c => c.ProductName.Equals(search)).ToList();
                    break;
                case "4":
                    serachModelout = lsModelout.Where(c => c.ProductInfo.Equals(search)).ToList();
                    break;
                case "5":
                    serachModelout = lsModelout.Where(c => c.ProductCharge.Equals(search)).ToList();
                    break;
                case "6":
                    serachModelout = lsModelout.Where(c => c.ProductCounts.ToString().Equals(search)).ToList();
                    break;
                case "7":
                    serachModelout = lsModelout.Where(c => c.ProductUnitDays.ToString().Equals(search)).ToList();
                    break;
                case "8":
                    serachModelout = lsModelout.Where(c => c.ProductUnitPrice.ToString().Equals(search)).ToList();
                    break;
                case "9":
                    serachModelout = lsModelout.Where(c => c.ProductRemarks1.Equals(search)).ToList();
                    break;
                case "10":
                    serachModelout = lsModelout.Where(c => c.ProductRemarks2.Equals(search)).ToList();
                    break;
                case "11":
                    serachModelout = lsModelout.Where(c => c.ProductDays.ToString().Equals(search)).ToList();
                    break;
                case "12":
                    serachModelout = lsModelout.Where(c => c.ProductCreateDate.Date.ToString("yyyy/MM/dd").Equals(search)).ToList();
                    break;
                case "13":
                    serachModelout = lsModelout.Where(c => c.ProductChangeDate.ToString("yyyy/MM/dd HH:mm").Equals(search)).ToList();
                    break;
                default:
                    serachModelout = lsModelout.Where(c => c.ProductName.Equals(search)).ToList();
                    break;
            }

            string JsonDataout = JsonConvert.SerializeObject(serachModelout);
            TempData["save"] = JsonDataout;
            ViewData["search"] = search;
            ViewData["searchSelect"] = searchSelect;
            ViewData["FuzzyOrNormal"] = true;
            var pageCnt = page;
            var pageRows = pageRowCount;
            var querylsModel = serachModelout.Skip((pageCnt - 1) * pageRows).Take(pageRows);
            int listConut = (serachModelout.Count / pageRowCount) + 1;
            if (serachModelout.Count % pageRowCount > 0) listConut += 1;
            var pageNext = pageCnt + 1;
            if (pageNext >= listConut - 1) pageNext = listConut - 1;
            var pagePrev = pageCnt - 1;
            if (pagePrev <= 1) pagePrev = 1;
            ViewData["pageNext"] = pageNext;
            ViewData["pagePrev"] = pagePrev;
            int listConutStart = 0;
            int listConutEnd = 10;
            var pageRowsQuantity = 5;
            if (page <= pageRowsQuantity)
            {
                listConutStart = 1;
                listConutEnd = 10;
            }
            else
            {
                listConutStart = page - pageRowsQuantity;
                listConutEnd = page + pageRowsQuantity - 1;
            }
            if (listConutStart <= 1) listConutStart = 1;
            if (listConutEnd > listConut) listConutEnd = listConut - 1;
            ViewData["listConut"] = listConut;
            ViewData["page"] = page;
            ViewData["listConutStart"] = listConutStart;
            ViewData["listConutEnd"] = listConutEnd;
            ViewData["CountModel"] = querylsModel.Count();
            return View(querylsModel);
        }

        public ActionResult FuzzySearchView(string search="", string searchSelect="1", int page = 1)
        {

            string strlsModel = (string)TempData["save"];
            List<MarkSalesOrderModel> lsModelout = JsonConvert.DeserializeObject<List<MarkSalesOrderModel>>(strlsModel);
  
            if (search == null) search = "";         
            List<MarkSalesOrderModel> serachModelout;
            switch (searchSelect)
            {
                case "1":
                    serachModelout = lsModelout.Where(c => c.MemberEmail.IndexOf(search) > -1).ToList();
                    break;
                case "2":
                    serachModelout = lsModelout.Where(c => c.MemberName.IndexOf(search) > -1).ToList();
                    break;
                case "3":
                    serachModelout = lsModelout.Where(c => c.ProductName.IndexOf(search) > -1).ToList();
                    break;
                case "4":
                    serachModelout = lsModelout.Where(c => c.ProductInfo.IndexOf(search) > -1).ToList();
                    break;
                case "5":
                    serachModelout = lsModelout.Where(c => c.ProductCharge.IndexOf(search) > -1).ToList();
                    break;
                case "6":
                    serachModelout = lsModelout.Where(c => c.ProductCounts.ToString().IndexOf(search) > -1).ToList();
                    break;
                case "7":
                    serachModelout = lsModelout.Where(c => c.ProductUnitDays.ToString().IndexOf(search) > -1).ToList();
                    break;
                case "8":
                    serachModelout = lsModelout.Where(c => c.ProductUnitPrice.ToString().IndexOf(search) > -1).ToList();
                    break;
                case "9":
                    serachModelout = lsModelout.Where(c => c.ProductRemarks1.IndexOf(search) > -1).ToList();
                    break;
                case "10":

edit20210325/Areas/AdminKfTBoRdp7z/Views/SalesOrder/Create.cshtml
@model edit20210325.Models.SalesOrderModel

@{
    ViewData["Title"] = "製成品建立";
    ViewData["ＰageCtrl"] = "1";
}

<h1>製成品建立</h1>
<hr />
<script>
    $(document).ready(function () {
        changFunc();
    });
    function changFunc() {
        @{
            var json = Newtonsoft.Json.JsonConvert.SerializeObject((IEnumerable<edit20210325.Models.MemberModel>)ViewBag.ModelList);
         }
        var memberId = document.getElementById("MemberId").value;
        var JsonString = @Html.Raw(json);
        for (var i = 0; i < JsonString.length; i++) {
            if (JsonString[i].Id == memberId) {
                document.getElementById("memberName").innerHTML = "會員名稱："+JsonString[i].MemberName;
            }
        }
    }
</script>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductDays" class="form-control" value="0" />
            <div class="form-group">
                <label asp-for="MemberId" class="control-label"></label>
                <select asp-for="MemberId" class="form-control" onchange="changFunc()">
                    @{ var modelList = (IEnumerable<edit20210325.Models.MemberModel>)ViewBag.ModelList;}
                    @foreach (var it in modelList)
                    {
                        <option value="@it.Id">@it.MemberName@(": ")@it.MemberGmail</option>
                    }
                </select>
                <span asp-validation-for="MemberId" class="text-danger"></span>
                <P id="memberName"></P>
            </div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductInfo" class="control-label"></label><br>
                <textarea asp-for="ProductInfo" class="form-control" rows="6" cols="30"></textarea>
                <span asp-validation-for="ProductInfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCharge" class="control-label"></label>
                <select asp-for="ProductCharge" class="form-control">
                    <option value="期間">期間</option>
                    <option value="計次">計次</option>
                </select>
                <span asp-validation-for="ProductCharge" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCounts" class="control-label"></label>
                <input asp-for="ProductCounts" class="form-control" />
                <span asp-validation-for="ProductCounts" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductUnitDays" class="control-label"></label>
                <input asp-for="ProductUnitDays" class="form-control" />
                <span asp-validation-for="ProductUnitDays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductUnitPrice" class="control-label"></label>
                <input asp-for="ProductUnitPrice" class="form-control" />
                <span asp-validation-for="ProductUnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductRemarks1" class="control-label"></label>
                <textarea asp-for="ProductRemarks1" class="form-control" rows="6" cols="30"></textarea>
                <span asp-validation-for="ProductRemarks1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductRemarks2" class="control-label"></label>
                <textarea asp-for="ProductRemarks2" class="form-control" rows="6" cols="30"></textarea>
                <span asp-validation-for="ProductRemarks2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCreateDate" class="control-label"></label>
                <input asp-for="ProductCreateDate" type="date" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                <span asp-validation-for="ProductCreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductChangeDate" class="control-label"></label>
                <input asp-for="ProductChangeDate" class="form-control" />
                <span asp-validation-for="ProductChangeDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="建立" class="btn btn-primary onDivLeft" />

                <button id="btnExit" class="btn btn-primary onDivRight cancel" asp-action="exit">取消</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

edit20210325/Areas/AdminKfTBoRdp7z/Views/SalesOrder/FuzzySearchView.cshtml
@model IEnumerable<edit20210325.ViewModels.MarkSalesOrderModel>
@{
    var pathName = edit20210325.Function.ProjectSet.AdminName;
}
@{
    ViewData["Title"] = "製成品總表";
    ViewData["ＰageCtrl"] = "1";
}

<h1>製成品總表</h1>
<h4>查詢條件</h4>
<form class="form-inline  " role="form">
    <div class="form-group m-0 p-0 mr-auto">
        <label for="searchSelect">搜尋欄位:&ensp;</label>
        <select Name="searchSelect" id="searchSelectId" onchange="searchSelectFunc()">
            @if ((string)ViewData["searchSelect"] == "1")
            {
                <option value="1" selected>@Html.DisplayNameFor(model => model.MemberEmail)</option>
            }
            else
            {
                <option value="1">@Html.DisplayNameFor(model => model.MemberEmail)</option>
            }
            @if ((string)ViewData["searchSelect"] == "2")
            {
                <option value="2" selected>@Html.DisplayNameFor(model => model.MemberName)</option>
            }
            else
            {
                <option value="2">@Html.DisplayNameFor(model => model.MemberName)</option>
            }
            @if ((string)ViewData["searchSelect"] == "3")
            {
                <option value="3" selected>@Html.DisplayNameFor(model => model.ProductName)</option>
            }
            else
            {
                <option value="3">@Html.DisplayNameFor(model => model.ProductName)</option>
            }
            @if ((string)ViewData["searchSelect"] == "4")
            {
                <option value="6" selected>@Html.DisplayNameFor(model => model.ProductInfo)</option>

            }
            else
            {
                <option value="6">@Html.DisplayNameFor(model => model.ProductInfo)</option>

            }
            @if ((string)ViewData["searchSelect"] == "5")
            {
                <option value="5" selected>@Html.DisplayNameFor(model => model.ProductCharge)</option>

            }
            else
            {
                <option value="5">@Html.DisplayNameFor(model => model.ProductCharge)</option>

            }
            @if ((string)ViewData["searchSelect"] == "6")
            {
                <option value="6" selected>@Html.DisplayNameFor(model => model.ProductCounts)</option>

            }
            else
            {
                <option value="6">@Html.DisplayNameFor(model => model.ProductCounts)</option>

            }
            @if ((string)ViewData["searchSelect"] == "7")
            {
                <option value="7" selected>@Html.DisplayNameFor(model => model.ProductUnitDays)</option>

            }
            else
            {
                <option value="7">@Html.DisplayNameFor(model => model.ProductUnitDays)</option>

            }
            @if ((string)ViewData["searchSelect"] == "8")
            {
                <option value="8" selected>@Html.DisplayNameFor(model => model.ProductUnitPrice)</option>

            }
            else
            {
                <option value="8">@Html.DisplayNameFor(model => model.ProductUnitPrice)</option>

            }
            @if ((string)ViewData["searchSelect"] == "9")
            {
                <option value="9" selected>@Html.DisplayNameFor(model => model.ProductRemarks1)</option>

            }
            else
            {
                <option value="9">@Html.DisplayNameFor(model => model.ProductRemarks1)</option>

            }
            @if ((string)ViewData["searchSelect"] == "10")
            {
                <option value="10" selected>@Html.DisplayNameFor(model => model.ProductRemarks2)</option>

            }
            else
            {
                <option value="10">@Html.DisplayNameFor(model => model.ProductRemarks2)</option>

            }
            @if ((string)ViewData["searchSelect"] == "11")
            {
                <option value="11" selected>@Html.DisplayNameFor(model => model.ProductDays)</option>

            }
            else
            {
                <option value="11">@Html.DisplayNameFor(model => model.ProductDays)</option>

            }

            @if ((string)ViewData["searchSelect"] == "12")
            {
                <option value="12" selected>@Html.DisplayNameFor(model => model.ProductCreateDate)</option>
            }
            else
            {
                <option value="12">@Html.DisplayNameFor(model => model.ProductCreateDate)</option>
            }
            @if ((string)ViewData["searchSelect"] == "13")
            {
                <option value="13" selected>@Html.DisplayNameFor(model => model.ProductChangeDate)</option>
            }
            else
            {
                <option value="13">@Html.DisplayNameFor(model => model.ProductChangeDate)</option>
            }
        </select>
    </div>
    <div class=" form-group  m-0 p-0">
        <label for="search" style="width:auto">關鍵字:&ensp;</label>
        <input type="text" name="search" id="searchId" value="@ViewData["search"]" />&ensp;
    </div>
    <div class=" form-group  m1-1 p-0 ">
        <label class="m-0 p-0" for="RadioModelId">比對模式:</label>
        <div class="form-control-sm">
            @Html.RadioButton("RadioModelId", "fuzzyMatch", true, new { id = "RadioModelId2", @class = " p-0" })包含關鍵字<br>
            @Html.RadioButton("RadioModelId", "keyMatch", false, new { id = "RadioModelId1", @class = "p-0" })關鍵字相同<br>
        </div>
    </div>
    <div class=" form-group  m-0 p-0  m1-2 ">
        <input type="button" value="開始搜尋" onclick="SearchFunc('SalesOrder','@pathName')" />
    </div>


</form>
<hr style="background-color:#808080">
<div class="form-inline">
    <input type="button" class="mb-1 mr-auto" value="檢視所有資料" onclick="location.href='@Url.Action("Index", "SalesOrder",new { FuzzyOrNormal = false,search = (string)ViewData["search"], searchSelect = (string)ViewData["searchSelect"],page=1})'" />
    <input type="button" class="mb-1" value="新增製成品" onclick="location.href='@Url.Action("Create", "SalesOrder")'" />
</div>



<table class="table tbl-list" style="border:2px  #808080 solid; width:100%" id="tableId" cellpadding="0" cellspacing="0">
    <thead>
        <tr style="background-color: #c7c7c7;">
            <th style="border:1px  #808080 solid;"></th>
            <th style="border:1px  #808080 solid;"></th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 2, 'string')">
                @Html.DisplayNameFor(model => model.MemberEmail)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 3, 'string')">
                @Html.DisplayNameFor(model => model.MemberName)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 4, 'string')">
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 5, 'string')">
                @Html.DisplayNameFor(model => model.ProductInfo)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 6, 'string')">
                @Html.DisplayNameFor(model => model.ProductCharge)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 7, 'int')">
                @Html.DisplayNameFor(model => model.ProductCounts)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 8, 'int')">
                @Html.DisplayNameFor(model => model.ProductUnitDays)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 9, 'int')">
                @Html.DisplayNameFor(model => model.ProductUnitPrice)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 10, 'string')">
                @Html.DisplayNameFor(model => model.ProductRemarks1)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 11, 'string')">
                @Html.DisplayNameFor(model => model.ProductRemarks2)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 12, 'int')">
                @Html.DisplayNameFor(model => model.ProductDays)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 13, 'date')">
                @Html.DisplayNameFor(model => model.ProductCreateDate)
            </th>
            <th style="border: 1px #808080 solid;cursor: pointer;"
                onclick="sortAble(this,'tableId', 14, 'date')">
                @Html.DisplayNameFor(model => model.ProductChangeDate)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <!--@Html.ActionLink("編輯", "Edit", new {  id=item.Id  })    -->
                <input type="button" value="編輯" onclick="location.href='@Url.Action("Edit", "SalesOrder", new {  id=item.Id  })'" />
            </td>
            <td>
                <!--@Html.ActionLink("刪除", "Delete", new {  id=item.Id})-->
                <input type="button" value="刪除" onclick="Delete('@item.ProductName','@Url.Action("Delete", "SalesOrder", new {  id=item.Id  })')" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
<textarea style="resize: none;border:0px;" rows="6" cols="6" readonly>
 @Html.DisplayFor(modelItem => item.ProductInfo)
</textarea>             
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductCharge)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductCounts)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductUnitDays)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductUnitPrice)
            </td>
            <td>
<textarea style="resize: none;border:0px;" rows="6" cols="2" readonly>
@Html.DisplayFor(modelItem => item.ProductRemarks1)
</textarea>
                
            </td>
            <td>
<textarea style="resize: none;border:0px;" rows="6" cols="2" readonly>
@Html.DisplayFor(modelItem => item.ProductRemarks2)
</textarea>
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDays)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductCreateDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductChangeDate)
            </td>
        </tr>
        }
    </tbody>
</table>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item ">
            @if ((int)ViewData["CountModel"] > 0)
            {
                <button class="page-link" onclick="location.href='@Url.Action("FuzzySearchView", "SalesOrder", new { search = ViewData["search"], searchSelect = ViewData["searchSelect"], page = ViewData["pagePrev"] })'">&lt;</button>
            }
        </li>

        @for (int i = (int)ViewData["listConutStart"]; i <= (int)ViewData["listConutEnd"]; i++)
        {
            if (i == (int)ViewData["page"])
            {
                <li class="page-item">
                    <label class="page-link" style="color:red" onclick="location.href='@Url.Action("FuzzySearchView", "SalesOrder", new { search=ViewData["search"],searchSelect=ViewData["searchSelect"],  page=i })'">&ensp;[@i]&ensp;</label>
                </li>
            }
            else
            {
                <li class="page-item">
                    <label class="page-link" style="color:black" onclick="location.href='@Url.Action("FuzzySearchView", "SalesOrder", new { search=ViewData["search"],searchSelect=ViewData["searchSelect"],  page=i })'">&ensp;[@i]&ensp;</label>
                </li>
            }
        }
        <li class="page-item">
            @if ((int)ViewData["CountModel"] > 0)
            {
                <button class="page-link" onclick="location.href='@Url.Action("FuzzySearchView", "SalesOrder", new {search=ViewData["search"],searchSelect=ViewData["searchSelect"],   page= ViewData["pageNext"] })'">&gt;</button>
            }
        </li>
    </ul>
</nav>